/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : Cpu.C
**     Project   : Dilute_Test
**     Processor : MC9S08DZ60MLC
**     Component : MC9S08DZ60_32
**     Version   : Component 01.042, Driver 01.35, CPU db: 3.00.019
**     Datasheet : MC9S08DZ60 Rev. 3 10/2007
**     Compiler  : CodeWarrior HCS08 C Compiler
**     Date/Time : 2020/6/13, 15:24
**     Abstract  :
**         This bean "MC9S08DZ60_32" contains initialization of the
**         CPU and provides basic methods and events for CPU core
**         settings.
**     Settings  :
**
**     Contents  :
**         EnableInt  - void Cpu_EnableInt(void);
**         DisableInt - void Cpu_DisableInt(void);
**
**     Copyright : 1997 - 2009 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

/* MODULE Cpu. */

#pragma MESSAGE DISABLE C4002 /* WARNING C4002: Result not used is ignored */

#include "RS485W_EN.h"
#include "Uart.h"
#include "LED.h"
#include "TI1.h"
#include "SPI7708CS.h"
#include "SPI7708CLK.h"
#include "SPI7708SDI.h"
#include "SPI7708SDO.h"
#include "MYEEPROM.h"
#include "SPI7708EN.h"
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Events.h"
#include "Cpu.h"


/* Global variables */
volatile byte CCR_reg;                 /* Current CCR register */

/*Definition of global shadow variables*/
byte Shadow_PTB;
byte Shadow_PTD;


/*
** ===================================================================
**     Method      :  Cpu_Interrupt (component MC9S08DZ60_32)
**
**     Description :
**         The method services unhandled interrupt vectors.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(Cpu_Interrupt)
{
  /* This code can be changed using the CPU bean property "Build Options / Unhandled int code" */
  asm(BGND);
}


/*
** ===================================================================
**     Method      :  Cpu_DisableInt (component MC9S08DZ60_32)
**
**     Description :
**         Disables maskable interrupts
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Cpu_DisableInt(void)

**      This method is implemented as macro in the header module. **
*/

/*
** ===================================================================
**     Method      :  Cpu_EnableInt (component MC9S08DZ60_32)
**
**     Description :
**         Enables maskable interrupts
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Cpu_EnableInt(void)

**      This method is implemented as macro in the header module. **
*/

/*
** ===================================================================
**     Method      :  _EntryPoint (component MC9S08DZ60_32)
**
**     Description :
**         Initializes the whole system like timing and so on. At the end 
**         of this function, the C startup is invoked to initialize stack,
**         memory areas and so on.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
extern void _Startup(void);            /* Forward declaration of external startup function declared in file Start12.c */

#pragma NO_FRAME
#pragma NO_EXIT
void _EntryPoint(void)
{
  /* ### MC9S08DZ60_32 "Cpu" init code ... */
  /*  PE initialization code after reset */

  /* Common initialization of the write once registers */
  /* SOPT1: COPT=0,STOPE=0,SCI2PS=0,IICPS=0,??=0,??=0,??=0 */
  setReg8(SOPT1, 0x00);                 
  /* SOPT2: COPCLKS=0,COPW=0,??=0,ADHTS=0,??=0,MCSEL=0 */
  setReg8(SOPT2, 0x00);                 
  /* SPMSC1: LVWF=0,LVWACK=0,LVWIE=0,LVDRE=1,LVDSE=1,LVDE=1,??=0,BGBE=0 */
  setReg8(SPMSC1, 0x1C);                
  /* SPMSC2: ??=0,??=0,LVDV=0,LVWV=0,PPDF=0,PPDACK=0,??=0,PPDC=0 */
  setReg8(SPMSC2, 0x00);                
  /*  System clock initialization */
  if (*(unsigned char*)0xFFAF != 0xFF) { /* Test if the device trim value is stored on the specified address */
    MCGTRM = *(unsigned char*)0xFFAF;  /* Initialize MCGTRM register from a non volatile memory */
    MCGSC = *(unsigned char*)0xFFAE;   /* Initialize MCGSC register from a non volatile memory */
  }
  /* MCGC2: BDIV=0,RANGE=1,HGO=0,LP=0,EREFS=1,ERCLKEN=1,EREFSTEN=0 */
  setReg8(MCGC2, 0x26);                /* Set MCGC2 register */ 
  /* MCGC1: CLKS=2,RDIV=7,IREFS=0,IRCLKEN=1,IREFSTEN=0 */
  setReg8(MCGC1, 0xBA);                /* Set MCGC1 register */ 
  while(!MCGSC_OSCINIT) {              /* Wait until external reference is stable */
  }
  while(MCGSC_IREFST) {                /* Wait until external reference is selected */
  }
  while((MCGSC & 0x0C) != 0x08) {      /* Wait until external clock is selected as a bus clock reference */
  }
  /* MCGC2: BDIV=0,RANGE=1,HGO=0,LP=1,EREFS=1,ERCLKEN=1,EREFSTEN=0 */
  setReg8(MCGC2, 0x2E);                /* Set MCGC2 register */ 
  /* MCGC1: CLKS=2,RDIV=2,IREFS=0,IRCLKEN=1,IREFSTEN=0 */
  setReg8(MCGC1, 0x92);                /* Set MCGC1 register */ 
  /* MCGC3: LOLIE=0,PLLS=1,CME=0,??=0,VDIV=4 */
  setReg8(MCGC3, 0x44);                /* Set MCGC3 register */ 
  /* MCGC2: LP=0 */
  clrReg8Bits(MCGC2, 0x08);             
  while(!MCGSC_PLLST) {                /* Wait until PLL is selected */
  }
  while(!MCGSC_LOCK) {                 /* Wait until PLL is locked */
  }
  /* MCGC1: CLKS=0,RDIV=2,IREFS=0,IRCLKEN=1,IREFSTEN=0 */
  setReg8(MCGC1, 0x12);                /* Set MCGC1 register */ 
  while((MCGSC & 0x0C) != 0x0C) {      /* Wait until PLL clock is selected as a bus clock reference */
  }
  
  /*** End of PE initialization code after reset ***/
  __asm   jmp _Startup ;               /* Jump to C startup code */

}

/*
** ===================================================================
**     Method      :  PE_low_level_init (component MC9S08DZ60_32)
**
**     Description :
**         Initializes beans and provides common register initialization. 
**         The method is called automatically as a part of the 
**         application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void PE_low_level_init(void)
{
  /* Common initialization of the CPU registers */
  /* PTAD: PTAD7=0,PTAD6=0,PTAD5=0,PTAD4=0,PTAD3=0,PTAD2=0,PTAD1=0,PTAD0=0 */
  setReg8(PTAD, 0x00);                  
  /* PTAPE: PTAPE7=0 */
  clrReg8Bits(PTAPE, 0x80);             
  /* PTADD: PTADD7=1,PTADD6=1,PTADD5=1,PTADD4=1,PTADD3=1,PTADD2=1,PTADD1=1,PTADD0=1 */
  setReg8(PTADD, 0xFF);                 
  /* PTED: PTED7=0,PTED6=0,PTED4=0,PTED3=0,PTED2=1,PTED0=1 */
  clrSetReg8Bits(PTED, 0xD8, 0x05);     
  /* PTEDD: PTEDD7=1,PTEDD6=1,PTEDD5=0,PTEDD4=1,PTEDD3=1,PTEDD2=1,PTEDD1=0,PTEDD0=1 */
  setReg8(PTEDD, 0xDD);                 
  /* PTBD: PTBD7=0,PTBD6=0,PTBD5=0,PTBD4=0,PTBD3=0,PTBD2=0,PTBD1=1,PTBD0=0 */
  setReg8(PTBD, 0x02);                  
  /* PTBPE: PTBPE1=0 */
  clrReg8Bits(PTBPE, 0x02);             
  /* PTBDD: PTBDD7=1,PTBDD6=1,PTBDD5=1,PTBDD4=1,PTBDD3=1,PTBDD2=1,PTBDD1=1,PTBDD0=1 */
  setReg8(PTBDD, 0xFF);                 
  /* PTEPE: PTEPE5=1,PTEPE4=0,PTEPE3=0,PTEPE2=0 */
  clrSetReg8Bits(PTEPE, 0x1C, 0x20);    
  /* PTDD: PTDD7=0,PTDD6=0,PTDD5=0,PTDD4=0,PTDD3=0,PTDD2=0,PTDD1=0,PTDD0=0 */
  setReg8(PTDD, 0x00);                  
  /* PTDPE: PTDPE0=0 */
  clrReg8Bits(PTDPE, 0x01);             
  /* PTDDD: PTDDD7=1,PTDDD6=1,PTDDD5=1,PTDDD4=1,PTDDD3=1,PTDDD2=1,PTDDD1=1,PTDDD0=1 */
  setReg8(PTDDD, 0xFF);                 
  /* PTASE: PTASE7=0,PTASE6=0,PTASE5=0,PTASE4=0,PTASE3=0,PTASE2=0,PTASE1=0,PTASE0=0 */
  setReg8(PTASE, 0x00);                 
  /* PTBSE: PTBSE1=0,PTBSE0=0 */
  clrReg8Bits(PTBSE, 0x03);             
  /* PTDSE: PTDSE5=0,PTDSE4=0,PTDSE3=0,PTDSE2=0,PTDSE1=0,PTDSE0=0 */
  clrReg8Bits(PTDSE, 0x3F);             
  /* PTESE: PTESE7=0,PTESE6=0,PTESE5=0,PTESE4=0,PTESE3=0,PTESE2=0,PTESE0=0 */
  clrReg8Bits(PTESE, 0xFD);             
  /* PTGSE: PTGSE1=0,PTGSE0=0 */
  clrReg8Bits(PTGSE, 0x03);             
  /* PTADS: PTADS7=1,PTADS6=1,PTADS5=1,PTADS4=1,PTADS3=1,PTADS2=1,PTADS1=1,PTADS0=1 */
  setReg8(PTADS, 0xFF);                 
  /* PTBDS: PTBDS7=0,PTBDS6=0,PTBDS5=0,PTBDS4=0,PTBDS3=0,PTBDS2=0,PTBDS1=1,PTBDS0=1 */
  setReg8(PTBDS, 0x03);                 
  /* PTDDS: PTDDS7=0,PTDDS6=0,PTDDS5=1,PTDDS4=1,PTDDS3=1,PTDDS2=1,PTDDS1=1,PTDDS0=1 */
  setReg8(PTDDS, 0x3F);                 
  /* PTEDS: PTEDS7=1,PTEDS6=1,PTEDS5=1,PTEDS4=1,PTEDS3=1,PTEDS2=1,PTEDS1=0,PTEDS0=1 */
  setReg8(PTEDS, 0xFD);                 
  /* PTGDS: ??=0,??=0,PTGDS5=0,PTGDS4=0,PTGDS3=0,PTGDS2=0,PTGDS1=1,PTGDS0=1 */
  setReg8(PTGDS, 0x03);                 
  /* PTCD: PTCD7=0,PTCD6=0,PTCD5=0,PTCD4=0,PTCD3=0,PTCD2=0,PTCD1=0,PTCD0=0 */
  setReg8(PTCD, 0x00);                  
  /* PTCDD: PTCDD7=1,PTCDD6=1,PTCDD5=1,PTCDD4=1,PTCDD3=1,PTCDD2=1,PTCDD1=1,PTCDD0=1 */
  setReg8(PTCDD, 0xFF);                 
  /* PTFD: PTFD7=0,PTFD6=0,PTFD5=0,PTFD4=0,PTFD3=0,PTFD2=0,PTFD1=0,PTFD0=0 */
  setReg8(PTFD, 0x00);                  
  /* PTFDD: PTFDD7=1,PTFDD6=1,PTFDD5=1,PTFDD4=1,PTFDD3=1,PTFDD2=1,PTFDD1=1,PTFDD0=1 */
  setReg8(PTFDD, 0xFF);                 
  /* PTGD: PTGD5=0,PTGD4=0,PTGD3=0,PTGD2=0 */
  clrReg8Bits(PTGD, 0x3C);              
  /* PTGDD: PTGDD5=1,PTGDD4=1,PTGDD3=1,PTGDD2=1 */
  setReg8Bits(PTGDD, 0x3C);             
  /* ### Shared modules init code ... */
  /* ### BitIO "RS485W_EN" init code ... */
  /* ### Asynchro serial "Uart" init code ... */
  Uart_Init();
  /* ### BitIO "LED" init code ... */
  Shadow_PTB |= (byte)0x02;            /* Initialize pin shadow variable bit */
  /* ### TimerInt "TI1" init code ... */
  TI1_Init();
  /* ### BitIO "SPI7708CS" init code ... */
  /* ### BitIO "SPI7708CLK" init code ... */
  /* ### BitIO "SPI7708SDI" init code ... */
  /* ### BitIO "SPI7708SDO" init code ... */
  /* ### IntEEPROM "MYEEPROM" init code ... */
  MYEEPROM_Init();
  /* ### BitIO "SPI7708EN" init code ... */
  Shadow_PTD &= (byte)~0x01;           /* Initialize pin shadow variable bit */
  __EI();                              /* Enable interrupts */
}

/* Initialization of the CPU registers in FLASH */

/* NVPROT: EPS=3,FPS=0x3F */
const unsigned char NVPROT_INIT @0x0000FFBD = 0xFF;

/* NVOPT: KEYEN=0,FNORED=1,EPGMOD=1,??=1,??=1,??=1,SEC1=1,SEC0=0 */
const unsigned char NVOPT_INIT @0x0000FFBF = 0x7E;

/* END Cpu. */

/*
** ###################################################################
**
**     This file was created by Processor Expert 3.07 [04.46]
**     for the Freescale HCS08 series of microcontrollers.
**
** ###################################################################
*/
